include: package:flutter_code_style/analysis_options.yaml

analyzer:
  errors:
    # until this is fixed https://github.com/dart-lang/linter/issues/2671
    # until this is released https://github.com/dart-lang/linter/issues/2692
    always_specify_types: info
