name: db_infra
description: A command-line tool that help to automate your release workflow.
version: 1.0.0
homepage: https://github.com/db_infra

publish_to: none

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:
  archive: ">=3.3.0 <4.0.0"
  args: ">=2.3.0 <3.0.0"
  bdlogging:
    git: https://github.com/MoovBuilder983/bdlogging.git
  collection: ">=1.15.0 <2.0.0"
  encrypt: ">=5.0.1 <5.1.0"
  ftpconnect: ^2.0.5
  gcloud: ">=0.8.6 <1.0.0"
  glob: '>=2.0.0 <3.0.0'
  googleapis_auth: ">=1.3.1 <2.0.0"
  http: ^1.1.0
  io: ^1.0.4
  jose: ^0.3.4
  json_annotation: ^4.8.1
  meta: ^1.9.0
  path: ^1.8.3

dev_dependencies:
  build_runner: any
  flutter_code_style:
    git: https://github.com/MoovBuilder983/flutter-code-style.git
  json_serializable: ^6.7.1
  test: ^1.24.4

executables:
  db_infra:
